#! /usr/bin/sh

mkdir bin/;

javac -d bin/ --release 11 src/*.java src/com/moura/*.java src/com/moura/components/*.java src/com/moura/actions/*.java

# Build Jar process
cd bin/;
jar -cmf ../MANIFEST.MF ../app.jar *.class com/moura/components/*.class com/moura/actions/*.class com/moura/*.class;
cd ..;
rm -r bin/;
echo "\033[;32mBuild process complete";
