#! /usr/bin/sh

# Delete any metadata editor installation
sudo rm -r /opt/metadata-editor/

# First, build the application
./build

sudo mkdir /opt/metadata-editor/
sudo mv app.jar /opt/metadata-editor/
sudo cp -r data/ /opt/metadata-editor/

# Paste the .desktop file in the user directory
cp *.desktop ~/.local/share/applications

