#! /usr/bin/sh

# uninstall any metadata editor installation
./uninstall

# First, build the application
./build

sudo mkdir /opt/metadata-editor/
sudo mv app.jar /opt/metadata-editor/
sudo cp -r data/ /opt/metadata-editor/

# Paste the .desktop file in the user directory
cp metadata-editor.desktop ~/.local/share/applications
