#! /usr/bin/sh

echo "\033[;32mRemoving desktop entry."
rm ~/.local/share/applications/metadata-editor.desktop

echo "Removing app and its data."
sudo rm -r /opt/metadata-editor

echo "Uninstallation process complete.\033[m"
